stages:
  download:
    cmd: python src/download.py
    deps:
    - src/download.py
    outs:
    - data/raw
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw/ames.csv
    - src/prepare.py
    outs:
    - data/processed/ames_with_correct_types.pkl
  clean:
    cmd: python src/clean.py
    deps:
    - data/processed/ames_with_correct_types.pkl
    - src/clean.py
    outs:
    - data/processed/ames_clean.pkl
  featurize:
    cmd: python src/featurize.py
    deps:
    - data/processed/ames_clean.pkl
    - src/featurize.py
    outs:
    - data/processed/ames_features.pkl
