name: ames_dvc
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyterlab
  - folium
  - yapf
  - seaborn
  - scikit-learn
  - requests
  - pip:
    - dvc
    - dvclive
    
